In [2]:
import os
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [10]:
df = pd.read_csv('/home/santiago/Documentos/archivosPruebas/avocado.csv', index_col=0)
df.head(10)

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany
5,2015-11-22,1.26,55979.78,1184.27,48067.99,43.61,6683.91,6556.47,127.44,0.0,conventional,2015,Albany
6,2015-11-15,0.99,83453.76,1368.92,73672.72,93.26,8318.86,8196.81,122.05,0.0,conventional,2015,Albany
7,2015-11-08,0.98,109428.33,703.75,101815.36,80.00,6829.22,6266.85,562.37,0.0,conventional,2015,Albany
8,2015-11-01,1.02,99811.42,1022.15,87315.57,85.34,11388.36,11104.53,283.83,0.0,conventional,2015,Albany
9,2015-10-25,1.07,74338.76,842.40,64757.44,113.00,8625.92,8061.47,564.45,0.0,conventional,2015,Albany

In [30]:
# Insertar Datos a un DataFrame

personas = {
    "Nombre": ["Juan Alberto", "Alberto pedrosa", "El pepi"],
    "Cedula": ["20410586", "20054440", "10446235"],
    "Edad": [20, 50, 25]
}

df = pd.DataFrame(personas)
df

# Metodo 1 Syntaxis Basica
df["Profesiones"] = ["Tecnico en vagancia", "Ingeniero en no Hacer nada", "Tecnico manipulador de Misiles"]
df
# Metodo 2 Usando assing
df = df.assign(Sueldo=[999999990, 5000000, 100]) # Columna nueva que se añade con los nuevos datos
df

# Metodo 3 Insert - Sirve por ejemplo si me falto colocar una columna en especifico, y requiero que vaya en orden
df.insert(3, "email", ["elmasdesocupado@gmail.com", "vago4life@gmail.com", "titocalderon@gmail.com"])
df

,Nombre,Cedula,Edad,email,Profesiones,Sueldo
0,Juan Alberto,20410586,20,elmasdesocupado@gmail.com,Tecnico en vagancia,999999990
1,Alberto pedrosa,20054440,50,vago4life@gmail.com,Ingeniero en no Hacer nada,5000000
2,El pepi,10446235,25,titocalderon@gmail.com,Tecnico manipulador de Misiles,100